export const OPTIONS_SANITIZE_TEXT_EDITOR = {
  allowedTags: ['h3', 'h4', 'h5', 'h6', 'blockquote', 'p', 'a', 'ul', 'ol',
    'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'code', 'hr', 'br', 'div', 'img',
    'table', 'thead', 'caption', 'tbody', 'tr', 'th', 'td', 'pre', 'iframe', 'span', 'font', 'u'],
  allowedAttributes: {
    '*': ['style'],
    img: ['src', 'alt'],
    font: ['color', 'size', 'face']
  },
  transformTags: {
    'img': (tagName, attribs) => {
      return {
        tagName,
        attribs: {
          ...attribs,
          style: 'max-width: 100%; width: 100%;'
        }
      }
    }
  }
}

export const CORS_PROXY = 'https://cors-anywhere.herokuapp.com/'

export const POPULAR_FEEDS = [
  'https://meduza.io/rss/all',
  'https://habr.com/ru/rss/best/daily/',
  'https://news.google.com/news/rss/headlines/section/topic/WORLD?ned=us&hl=en',
  'https://www.reddit.com/r/worldnews/.rss',
  'http://feeds.bbci.co.uk/news/world/rss.xml',
  'https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml',
  'https://www.buzzfeed.com/world.xml',
  'http://www.aljazeera.com/xml/rss/all.xml',
  'http://defence-blog.com/feed',
  'http://www.e-ir.info/category/blogs/feed',
  'http://www.globalissues.org/news/feed',
  'https://www.thecipherbrief.com/feed',
  'http://feeds.feedburner.com/WarNewsUpdates',
  'https://www.yahoo.com/news/world/rss',
  'http://rss.cnn.com/rss/edition_world.rss',
  'https://www.theguardian.com/world/rss',
  'http://feeds.reuters.com/Reuters/worldNews',
  'http://feeds.washingtonpost.com/rss/world',
  'http://timesofindia.indiatimes.com/rssfeeds/296589292.cms',
  'http://feeds.feedburner.com/ndtvnews-world-news',
  'https://www.rt.com/rss/news',
  'http://www.independent.co.uk/news/world/rss',
  'http://www.spiegel.de/international/index.rss',
  'http://www.npr.org/rss/rss.php?id=1004',
  'http://feeds.feedburner.com/daily-express-world-news',
  'https://www.cnbc.com/id/100727362/device/rss/rss.html',
  'http://www.mirror.co.uk/news/world-news/rss.xml',
  'http://www.cbc.ca/cmlink/rss-world',
  'http://feeds.feedburner.com/time/world',
  'https://www.cbsnews.com/latest/rss/world',
  'https://www.thesun.co.uk/news/worldnews/feed',
  'http://www.latimes.com/world/rss2.0.xml',
  'https://sputniknews.com/export/rss2/world/index.xml',
  'http://abcnews.go.com/abcnews/internationalheadlines',
  'http://www.abc.net.au/news/feed/52278/rss.xml',
  'https://www.vox.com/rss/world/index.xml',
  'http://feeds.skynews.com/feeds/rss/world.xml',
  'http://www.smh.com.au/rssheadlines/world/article/rss.xml',
  'http://en.rfi.fr/general/rss',
  'http://feeds.news24.com/articles/news24/World/rss',
  'http://www.rawstory.com/category/world/feed',
  'http://www.euronews.com/rss?level=theme&name=news',
  'https://www.thestar.com/feeds.articles.news.world.rss',
  'http://globalnews.ca/world/feed',
  'http://www.ctvnews.ca/rss/world/ctvnews-ca-world-public-rss-1.822289',
  'http://www.washingtontimes.com/rss/headlines/news/world',
  'http://www.france24.com/en/top-stories/rss',
  'http://www.seattletimes.com/nation-world/world/feed',
  'http://talkingpointsmemo.com/world-news/feed',
  'http://www.channelnewsasia.com/rssfeeds/8395884',
  'https://www.brookings.edu/topic/international-affairs/feed',
  'http://www.dailytelegraph.com.au/news/world/rss',
  'http://www1.cbn.com/cbnnews/world/feed',
  'http://www.todayonline.com/feed/world',
  'http://rss.csmonitor.com/feeds/world',
  'https://www.pri.org/stories/feed/everything',
  'https://www.rand.org/topics/international-affairs.xml/feed',
  'http://feeds.breakingnews.ie/bnworld',
  'https://www.thelocal.es/feeds/rss.php',
  'https://warontherocks.com/feed',
  'https://www.eveningexpress.co.uk/category/news/world/feed',
  'https://world.wng.org/taxonomy/term/72/feed',
  'http://ifpnews.com/feed',
  'https://www.neweurope.eu/category/world/feed',
  'https://blog.wan-ifra.org/feed/index.rss',
  'http://www.worldaffairsjournal.org/headlines.xml',
  'http://smallwarsjournal.com/rss/blogs',
  'https://cloutwork.com/feed',
  'https://newsdazzle.online/feed',
  'https://ppapiblogue.blogspot.com/feeds/posts/default?alt=rss',
  'http://usahint.com/feed',
  'http://justworldeducational.org/category/blog/feed',
  'https://newslanes.com/feed',
  'http://asiandefencenewschannel.blogspot.com/feeds/posts/default',
  'https://www.blogger.com/feeds/2886832199291333748/posts/default',
  'http://apushcurrentevents.blogspot.com/feeds/posts/default',
  'http://justworldnews.org/feed',
  'http://worldunitednews.blogspot.com/feeds/posts/default',
  'http://feeds.feedburner.com/cgsblog'
]
